train_path: "train"
valid_path: "valid"
test_path:  "test"

root: "static/data/engravings/gp_wk"


seed: 42
root_to_save_model: "models/engravings_models/test_new_sets_b3_wo_augs"
device: 'cuda:0' #'cpu'
updates_per_epoch: 0
# means we will train on full dataset


model:
  type: engravings.models.EngravingsEffnet
  efficientnet: 'efficientnet-b3'


optimizer:
  type: torch.optim.Adam
  lr: 0.0003


criterion:
  type: torch.nn.CrossEntropyLoss


dataset:
  type: engravings.data.EngravingsDataset


train_dataloader:
  batch_size: 32
  num_workers: 1

valid_dataloader:
  batch_size: 32
  num_workers: 1

test_dataloader:
  batch_size: 32
  num_workers: 1


# We have 3 stages:
# 1. train only head
# 2. train last (NUM_LAYERS - num_freeze_layers_on_2nd_stage) layers
# 3. train full network

num_freeze_layers_on_2nd_stage: 180
num_freeze_layers_on_3rd_stage: 160
num_freeze_layers_on_4th_stage: 150

###---1st stage---###
scheduler1:
  type: torch.optim.lr_scheduler.ReduceLROnPlateau
  factor: 0.1
  mode: 'min'
  verbose: True
  patience: 2
  cooldown: 0
  min_lr: 0

trainer1:
  type: engravings.models.EngravingsTrainer
  n_epochs: 40
  verbose: True
  save_info_txt: True
  earlystopping: True
  es_delta: 0
  es_patience: 7
  es_mode: 'loss'
#------------------#


###---2nd stage---###
scheduler2:
  type: torch.optim.lr_scheduler.ReduceLROnPlateau
  factor: 0.2
  mode: 'min'
  verbose: True
  patience: 2
  cooldown: 0
  min_lr: 0
  eps: 0.00000001
  threshold: 0.0001
  threshold_mode: 'rel'

trainer2:
  type: engravings.models.EngravingsTrainer
  n_epochs: 50
  verbose: True
  save_info_txt: True
  earlystopping: True
  es_delta: 0
  es_patience: 10
  es_mode: 'loss'
#------------------#


###---3rd stage---###
scheduler3:
  type: torch.optim.lr_scheduler.ReduceLROnPlateau
  factor: 0.2
  mode: 'min'
  verbose: True
  patience: 2
  cooldown: 0
  min_lr: 0
  eps: 0.00000001
  threshold: 0.0001
  threshold_mode: 'rel'

trainer3:
  type: engravings.models.EngravingsTrainer
  n_epochs: 50
  verbose: True
  save_info_txt: True
  earlystopping: True
  es_delta: 0
  es_patience: 10
  es_mode: 'loss'
#------------------#


###---4th stage---###
scheduler4:
  type: torch.optim.lr_scheduler.ReduceLROnPlateau
  factor: 0.3
  mode: 'min'
  verbose: True
  patience: 3
  cooldown: 0
  min_lr: 0
  eps: 0.00000001
  threshold: 0.0001
  threshold_mode: 'rel'

trainer4:
  type: engravings.models.EngravingsTrainer
  n_epochs: 300
  verbose: True
  save_info_txt: True
  earlystopping: True
  es_delta: 0
  es_patience: 10
  es_mode: 'loss'
#------------------#
