train_path: "static/data/csv/downsampling_age_train.csv"
valid_path: "static/data/csv/downsampling_age_valid.csv"
test_path:  "static/data/csv/downsampling_age_test.csv"

root: "static/data/data/"


seed: 42
root_to_save_model: "models/age_models/last_test"
device: 'cuda:0' #'cpu'
updates_per_epoch: 0
# means we will train on full dataset


model:
  type: agearts.models.AgeArtsEffnet
  efficientnet: 'efficientnet-b0'


optimizer:
  type: torch.optim.Adam
  lr: 0.01


criterion:
  type: torch.nn.MSELoss #L1Loss #MSELoss


dataset:
  type: agearts.data.AgeArtsDataset


train_dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: False

valid_dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: True

test_dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: True


# We have 3 stages:
# 1. train only head
# 2. train last (NUM_LAYERS - num_freeze_layers_on_2nd_stage) layers
# 3. train full network

num_freeze_layers_on_2nd_stage: 150
num_freeze_layers_on_3rd_stage: 80

###---1st stage---###
scheduler1:
  type: torch.optim.lr_scheduler.ReduceLROnPlateau
  factor: 0.1
  mode: 'min'
  verbose: True
  patience: 2
  cooldown: 0
  min_lr: 0

trainer1:
  type: agearts.models.AgeArtsTrainer
  n_epochs: 30
  verbose: True
  save_info_txt: True
  earlystopping: True
  es_delta: 0
  es_patience: 5
  es_mode: 'loss'
#------------------#


###---2nd stage---###
scheduler2:
  type: torch.optim.lr_scheduler.ReduceLROnPlateau
  factor: 0.2
  mode: 'min'
  verbose: True
  patience: 2
  cooldown: 0
  min_lr: 0
  eps: 0.00000001
  threshold: 0.0001
  threshold_mode: 'rel'

trainer2:
  type: agearts.models.AgeArtsTrainer
  n_epochs: 20
  verbose: True
  save_info_txt: True
  earlystopping: True
  es_delta: 0
  es_patience: 10
  es_mode: 'loss'
#------------------#


###---3rd stage---###
scheduler3:
  type: torch.optim.lr_scheduler.ReduceLROnPlateau
  factor: 0.2
  mode: 'min'
  verbose: True
  patience: 2
  cooldown: 0
  min_lr: 0
  eps: 0.00000001
  threshold: 0.0001
  threshold_mode: 'rel'

trainer3:
  type: agearts.models.AgeArtsTrainer
  n_epochs: 20
  verbose: True
  save_info_txt: True
  earlystopping: True
  es_delta: 0
  es_patience: 5
  es_mode: 'loss'
#------------------#


###---4th stage---###
scheduler4:
  type: torch.optim.lr_scheduler.ReduceLROnPlateau
  factor: 0.3
  mode: 'min'
  verbose: True
  patience: 3
  cooldown: 0
  min_lr: 0
  eps: 0.00000001
  threshold: 0.0001
  threshold_mode: 'rel'

trainer4:
  type: agearts.models.AgeArtsTrainer
  n_epochs: 300
  verbose: True
  save_info_txt: True
  earlystopping: True
  es_delta: 0
  es_patience: 10
  es_mode: 'loss'
#------------------#
