train_path: "static/data/csv/downsampling_age_train.csv"
valid_path: "static/data/csv/downsampling_age_valid.csv"
test_path:  "static/data/csv/downsampling_age_test.csv"

root: "static/data/data/"


seed: 42
root_to_save_model: "models/age2_models/last_test"
device: 'cuda:0' #'cpu'
updates_per_epoch: 0
# means we will train on full dataset


model:
  type: agearts.models.AgeArtEfficientnet
  path_to_searchart_model: '/home/juravlik/PycharmProjects/ssu_artworks/models/embedder_b0__fe_false__lr001__s25__m03__emb128/checkpoint.pt'
  feature_extracting: True


optimizer:
  type: torch.optim.Adam
  lr: 0.001


criterion:
  type: torch.nn.MSELoss #L1Loss #MSELoss


dataset:
  type: agearts.data.AgeArtsDataset


train_dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: False

valid_dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: True

test_dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: True



scheduler:
  type: torch.optim.lr_scheduler.ReduceLROnPlateau
  factor: 0.3
  mode: 'min'
  verbose: True
  patience: 1
  cooldown: 0
  min_lr: 0
  eps: 0.00000001
  threshold: 0.0001
  threshold_mode: 'rel'

trainer:
  type: agearts.models.AgeArtsTrainer
  n_epochs: 300
  verbose: True
  save_info_txt: True
  earlystopping: True
  es_delta: 0
  es_patience: 10
  es_mode: 'loss'
#------------------#
